### ISSUE TITLE
read_csv?

### ISSUE THREAD

**Issue by DaveBackus** [datasets/imf-weo#2]
I enjoyed looking through your code.  This might be obvious to you, but you can now read this in with pandas read_csv.  Code link below (somewhat of a work in progress), but here's a snippet:

import pandas as pd 
"""
Read data 
NB:  missing value list is critical, otherwise it doesn't recognize numbers 
Also:  file is tab-delimited, not xls, despite its name 
"""
url1 = 'http://www.imf.org/external/pubs/ft/weo/2015/01/weodata/'
url2 = 'WEOApr2015all.xls'
url = url1 + url2 
weo = pd.read_csv(url, sep='\t', thousands=',', na_values=['n/a', '--']) 

https://github.com/DaveBackus/Data_Bootcamp/blob/master/Code/Python/WEO_data_input.py

**Comment by rgrp** [comment]
@DaveBackus I know i can use pandas but i want minimal dependencies and this is very simple ;-)

BTW you may be interested in the Core Datasets project: http://okfnlabs.org/blog/2015/01/03/data-curators-wanted-for-core-datasets.html

**Comment by DaveBackus** [comment]
Perfect.
